# Generated by Django 5.2.6 on 2025-11-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_remove_video_video_url_video_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='skill',
        ),
        migrations.AddField(
            model_name='video',
            name='skills',
            field=models.ManyToManyField(to='MainApp.skill'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
