# Generated by Django 5.2.6 on 2025-11-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_rename_total_exp_profile_xp_remove_profile_peers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
