# Generated by Django 5.2.6 on 2025-11-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_remove_profile_education_remove_profile_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='MainApp.skill'),
        ),
    ]
